[tool.poetry]
name = "luhack_bot"
version = "0.1.0"
description = "LUHack's discord bot"
authors = [""]

[tool.poetry.dependencies]
python = "^3.7"
itsdangerous = "^1.1"
cryptography = "^2.7"
gino = "^0.8"
python-dotenv = "^0.10"
sqlalchemy_utils = "^0.34"
aiosmtplib = "^1.0"
aiomysql = "^0.0"
asyncpg = "^0.18"
alembic = "^1.0"
"sqlalchemy-searchable" = { tag = "1.1.2", git = "https://github.com/nitros12/sqlalchemy-searchable" }
starlette = "^0.12"
jinja2 = "^2.10"
python-multipart = "^0.0"
mistune = "^0.8"
pygments = "^2.4"
aiofiles = "^0.4"
slug = "^2.0"
WTForms = "^2.2"
yarl = "^1.3"
"discord.py" = "^1.2"
gunicorn = "^19.9"
uvicorn = {git = "https://github.com/nitros12/uvicorn"}
PyCrypto = "^2.6"
ujson = "^1.35"

[tool.poetry.dev-dependencies]
python-language-server = "^0.27"
psycopg2-binary = "^2.8"

[tool.poetry.scripts]
start_bot = 'luhack_bot:run'
gen_tokens = 'luhack_bot:gen_tokens'
export_users = 'luhack_bot:export_users'
ingest_users = 'luhack_bot:ingest_users'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

